[tool.poetry]
name = "umay"
version = "0.0.1"
description = "A speech handler"
authors = ["A O <adhambek.otabekov.post@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
cython = {optional=true, version = ">=3.0.2"}
setuptools-rust = {optional=true, version = ">=1.7.0"}
plug = {git = "https://github.com/aotabekov91/plug", branch='main'}

[tool.poetry.extras]
parser=["setuptools-rust", "cython"]

[tool.poetry.scripts]
umayc = "umay.cli:run"
umayd = "umay.main:run"
umayp = { callable = "umay.parser:run", extras = ["parser"] }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
